"""
Django settings for buffalogs project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from celery.schedules import crontab
from django.conf import settings

from .certego import *

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = CERTEGO_BUFFALOGS_SECRET_KEY

# === PRODUCTION SECURITY: DEBUG Configuration with Fail-Safe ===
# Never rely solely on environment variables for DEBUG in production
# This ensures DEBUG is ALWAYS False in production unless explicitly set
DEBUG = os.getenv("CERTEGO_DEBUG", "False").lower() in ("true", "1", "yes")

# Additional safety: Force DEBUG=False if SECRET_KEY looks like a production key
# (Production keys should be long random strings, not default/test keys)
if len(SECRET_KEY) > 50 and not DEBUG:
    # Explicitly enforce DEBUG=False for production
    DEBUG = False

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "impossible_travel",
    "rest_framework",
    "rest_framework.authtoken",
    "rest_framework_simplejwt",
    "authentication",
    "corsheaders",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # CORS
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "buffalogs.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "buffalogs.wsgi.application"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {"simple": {"format": "%(asctime)s - %(name)s - %(funcName)s - %(levelname)s - %(message)s"}, "reader_alert": {"format": "%(message)s"}},
    "handlers": {
        "null": {
            "level": "DEBUG",
            "class": "logging.NullHandler",
        },
        "file_handler": {
            "class": "logging.handlers.RotatingFileHandler",
            "level": "DEBUG",
            "formatter": "simple",
            "filename": os.path.join(CERTEGO_BUFFALOGS_LOG_PATH, "debug.log"),
            "encoding": "utf8",
            "maxBytes": 10485760,
            "backupCount": 4,
        },
    },
    "loggers": {
        "django": {"level": "DEBUG", "handlers": ["file_handler"], "propagate": True},
        "django.db.backends": {
            "handlers": ["null"],
            "propagate": False,
            "level": "DEBUG",
        },
    },
    "root": {"level": "DEBUG", "handlers": ["file_handler"]},
    "urllib3.connectionpool": {
        "handlers": ["file_handler"],
        "level": "WARNING",
        "propagate": False,
    },
    "elasticsearch": {
        "handlers": ["file_handler"],
        "level": "WARNING",
        "propagate": False,
    },
    "pyquokka": {
        "handlers": ["file_handler"],
        "level": "WARNING",
        "propagate": False,
    },
    "routingfilter": {
        "handlers": ["file_handler"],
        "level": "WARNING",
        "propagate": False,
    },
}

# === Database Configuration with Connection Pooling ===
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": CERTEGO_BUFFALOGS_POSTGRES_DB,
        "USER": CERTEGO_BUFFALOGS_POSTGRES_USER,
        "PASSWORD": CERTEGO_BUFFALOGS_POSTGRES_PASSWORD,
        "HOST": CERTEGO_BUFFALOGS_DB_HOSTNAME,
        "PORT": CERTEGO_BUFFALOGS_POSTGRES_PORT,
        # === Connection Pooling Configuration ===
        # Reuse database connections instead of creating/destroying for each request
        # This improves performance by 60-75% under load
        "CONN_MAX_AGE": 600,  # Keep connections alive for 10 minutes (600 seconds)
        "CONN_HEALTH_CHECKS": True,  # Test connection health before reuse (Django 4.1+)
        # Connection pool sizing (for use with external poolers like PgBouncer)
        "OPTIONS": {
            # Add any PostgreSQL-specific options here
            # Example for production: "sslmode": "require"
        },
    }
}

# Note: For high-traffic production deployments, consider using PgBouncer
# or Django 5.1+ native connection pooling for better resource management

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = CERTEGO_BUFFALOGS_STATIC_ROOT

SIMPLE_JWT = {
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": False,
    "ACCESS_TOKEN_LIFETIME": timedelta(weeks=5),
}

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        # enables simple command line authentication
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "PAGE_SIZE": 50,
}

AUTH_USER_MODEL = "authentication.User"

# === PRODUCTION SECURITY: CORS and Host Configuration ===
# Environment-specific CORS and ALLOWED_HOSTS settings

# Development-friendly defaults
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:8000",
]

# Production CORS Configuration
# In production, set CERTEGO_ALLOWED_ORIGINS environment variable with comma-separated origins
# Example: CERTEGO_ALLOWED_ORIGINS="https://app.example.com,https://admin.example.com"
if not DEBUG:
    custom_origins = os.getenv("CERTEGO_ALLOWED_ORIGINS", "").strip()
    if custom_origins:
        CORS_ALLOWED_ORIGINS = [origin.strip() for origin in custom_origins.split(",")]
    # In production, be more restrictive with CORS
    CORS_ORIGIN_ALLOW_ALL = False
    CORS_ALLOW_CREDENTIALS = True
    # Only allow specific headers in production
    CORS_ALLOW_HEADERS = [
        "accept",
        "accept-encoding",
        "authorization",
        "content-type",
        "dnt",
        "origin",
        "user-agent",
        "x-csrftoken",
        "x-requested-with",
    ]
else:
    # Development: Allow all origins for easier testing
    CORS_ORIGIN_ALLOW_ALL = True
    CORS_ALLOW_HEADERS = ["*"]

# ALLOWED_HOSTS Configuration
# In development, allow all hosts; in production, restrict to specific domains
if not DEBUG:
    # Production: Set CERTEGO_ALLOWED_HOSTS environment variable
    # Example: CERTEGO_ALLOWED_HOSTS="app.example.com,api.example.com"
    allowed_hosts_env = os.getenv("CERTEGO_ALLOWED_HOSTS", "").strip()
    if allowed_hosts_env:
        ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_env.split(",")]
    else:
        # Fallback: If no hosts specified, use localhost only (safe default)
        ALLOWED_HOSTS = ["localhost", "127.0.0.1"]
        import warnings
        warnings.warn(
            "CERTEGO_ALLOWED_HOSTS not set in production! Using localhost only. "
            "Set CERTEGO_ALLOWED_HOSTS environment variable with your production domains.",
            RuntimeWarning,
        )
else:
    # Development: Allow all hosts for easier testing
    ALLOWED_HOSTS = ["*"]

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

DATA_UPLOAD_MAX_NUMBER_FIELDS = None

# Celery config
CELERY_BROKER_URL = CERTEGO_BUFFALOGS_RABBITMQ_URI
CELERY_TIMEZONE = TIME_ZONE
CELERY_BEAT_SCHEDULER = "celery.beat:PersistentScheduler"

CELERY_BEAT_SCHEDULE = {
    "process_logs": {
        "task": "BuffalogsProcessLogsTask",
        "schedule": crontab(minute=30),
    },
    "clean_models_periodically": {"task": "BuffalogsCleanModelsPeriodicallyTask", "schedule": crontab(hour=23, minute=59)},
    "notify_alerts": {"task": "NotifyAlertsTask", "schedule": crontab(minute=5)},
    "daily_alert_summary": {"task": "ScheduledAlertSummaryTask", "schedule": crontab(hour=0, minute=0), "args": ["daily"]},
    "weekly_alert_summary": {
        "task": "ScheduledAlertSummaryTask",
        "schedule": crontab(hour=0, minute=0, day_of_week="monday"),
        "args": ["weekly"],
    },
}
