version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/test/python_test"
    schedule:
      interval: "weekly"
      day: "tuesday"
    target-branch: "develop"

  - package-ecosystem: "npm"
    directory: "/test/node_test"
    schedule:
      interval: "weekly"
      day: "tuesday"
    target-branch: "develop"


  - package-ecosystem: "docker"
    directory: "/test/python_test"
    schedule:
      interval: "weekly"
      day: "tuesday"
    target-branch: "develop"


  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
    target-branch: "develop"

