# Generated by Django 4.1.4 on 2023-04-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("impossible_travel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="updated",
            field=models.DateField(auto_now=True),
        ),
    ]
