# Generated by Django 5.2.9 on 2025-12-18 16:57

from django.db import migrations, models


def reset_filter_type_to_empty_list(apps, schema_editor):
    Alert = apps.get_model("impossible_travel", "Alert")
    Alert.objects.all().update(filter_type=[])


class Migration(migrations.Migration):

    dependencies = [
        ("impossible_travel", "0001_initial"),
    ]

    operations = [
        # First reset existing data to an empty list JSON, so no cast is needed
        migrations.RunPython(reset_filter_type_to_empty_list, migrations.RunPython.noop),

        # Then alter the field type
        migrations.AlterField(
            model_name="alert",
            name="filter_type",
            field=models.JSONField(
                default=list,
                blank=True,
                help_text="List of filters that disabled the related alert",
            ),
        ),
    ]

