# Generated by Django 4.1.4 on 2023-04-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("impossible_travel", "0002_alert_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
