# Generated by Django 5.2.9 on 2025-12-20 20:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impossible_travel', '0002_alter_alert_filter_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('suspicious_ip', 'Suspicious IP'), ('tor_exit_node', 'TOR Exit Node'), ('impossible_travel', 'Impossible Travel'), ('vpn', 'VPN')], max_length=50), blank=True, default=list, help_text='Select one or more tags', size=None),
        ),
    ]
