# Generated by Django 4.1.4 on 2023-04-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("impossible_travel", "0003_alter_alert_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="login",
            name="index",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
