# Generated by Django 4.1.4 on 2023-05-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("impossible_travel", "0005_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="is_vip",
            field=models.BooleanField(default=False),
        ),
    ]
