# Generated by Django 4.1.4 on 2023-05-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("impossible_travel", "0006_alert_is_vip"),
    ]

    operations = [
        migrations.AddField(
            model_name="login",
            name="event_id",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="login",
            name="ip",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
