# Generated by Django 4.1.4 on 2024-01-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "impossible_travel",
            "0009_config_ignored_ips_config_ignored_users_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="alert_max_days",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Days after which the alerts will be removed from the db",
            ),
        ),
        migrations.AddField(
            model_name="config",
            name="distance_accepted",
            field=models.PositiveIntegerField(
                default=100,
                help_text="Minimum distance (in Km) between two logins after which the impossible travel detection starts",
            ),
        ),
        migrations.AddField(
            model_name="config",
            name="ip_max_days",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Days after which the IPs will be removed from the db",
            ),
        ),
        migrations.AddField(
            model_name="config",
            name="login_max_days",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Days after which the logins will be removed from the db",
            ),
        ),
        migrations.AddField(
            model_name="config",
            name="user_max_days",
            field=models.PositiveIntegerField(
                default=60,
                help_text="Days after which the users will be removed from the db",
            ),
        ),
        migrations.AddField(
            model_name="config",
            name="vel_accepted",
            field=models.PositiveIntegerField(
                default=300,
                help_text="Minimum velocity (in Km/h) between two logins after which the impossible travel detection starts",
            ),
        ),
    ]
