# Generated by Django 5.1.6 on 2025-02-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "impossible_travel",
            "0012_remove_alert_valid_alert_filter_type_choices_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="notified",
            field=models.BooleanField(
                default=False,
                help_text="True when the alert has been notified by alerter",
            ),
        ),
    ]
