# Generated by Django 4.2.16 on 2025-02-28 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("impossible_travel", "0013_alert_notified"),
        ("impossible_travel", "0013_remove_alert_valid_alert_name_choice_and_more"),
    ]

    operations = []
