# Generated by Django 5.1.6 on 2025-03-05 10:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("impossible_travel", "0013_alert_notified"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="alert",
            name="valid_alert_name_choice",
        ),
        migrations.RemoveConstraint(
            model_name="config",
            name="valid_alert_filters_choices",
        ),
        migrations.AddField(
            model_name="config",
            name="max_ip_bruteforce",
            field=models.PositiveIntegerField(
                default=5, help_text="Maximum IP bruteforce attempts"
            ),
        ),
        migrations.AddField(
            model_name="config",
            name="max_login_bruteforce",
            field=models.PositiveIntegerField(
                default=5, help_text="Maximum login bruteforce attempts"
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="name",
            field=models.CharField(
                choices=[
                    ("New Device", "Login from new device"),
                    ("Imp Travel", "Impossible Travel detected"),
                    ("New Country", "Login from new country"),
                    ("User Risk Threshold", "User risk higher than threshold"),
                    ("Login Anonymizer Ip", "Login from an anonymizer IP"),
                    ("Atypical Country", "Login from a country not visited recently"),
                    ("Bruteforce User Login", "Bruteforce Detected on User"),
                    ("Bruteforce IP Login", "Bruteforce Detected from IP"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="config",
            name="filtered_alerts_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("New Device", "Login from new device"),
                        ("Imp Travel", "Impossible Travel detected"),
                        ("New Country", "Login from new country"),
                        ("User Risk Threshold", "User risk higher than threshold"),
                        ("Login Anonymizer Ip", "Login from an anonymizer IP"),
                        (
                            "Atypical Country",
                            "Login from a country not visited recently",
                        ),
                        ("Bruteforce User Login", "Bruteforce Detected on User"),
                        ("Bruteforce IP Login", "Bruteforce Detected from IP"),
                    ],
                    max_length=50,
                ),
                blank=True,
                default=list,
                help_text="List of alerts' types to exclude from the alerting",
                null=True,
                size=None,
            ),
        ),
        migrations.AddConstraint(
            model_name="alert",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "name__in",
                        [
                            "New Device",
                            "Imp Travel",
                            "New Country",
                            "User Risk Threshold",
                            "Login Anonymizer Ip",
                            "Atypical Country",
                            "Bruteforce User Login",
                            "Bruteforce IP Login",
                        ],
                    )
                ),
                name="valid_alert_name_choice",
            ),
        ),
        migrations.AddConstraint(
            model_name="config",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "filtered_alerts_types__contained_by",
                        [
                            "New Device",
                            "Imp Travel",
                            "New Country",
                            "User Risk Threshold",
                            "Login Anonymizer Ip",
                            "Atypical Country",
                            "Bruteforce User Login",
                            "Bruteforce IP Login",
                        ],
                    ),
                    ("filtered_alerts_types__isnull", True),
                    _connector="OR",
                ),
                name="valid_alert_filters_choices",
            ),
        ),
    ]
