# Generated by Django 4.2.19 on 2025-06-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("impossible_travel", "0014_config_risk_score_increment_alerts"),
    ]

    operations = [
        migrations.AddField(
            model_name="login",
            name="count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="login",
            name="outcome",
            field=models.CharField(default="success", max_length=15),
        ),
    ]
