# Generated by Django 5.1.7 on 2025-06-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("impossible_travel", "0014_config_risk_score_increment_alerts"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(
                db_index=True, default=None, max_length=255, unique=True
            ),
        ),
    ]
