# Generated by Django 4.2.19 on 2025-03-07 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("impossible_travel", "0014_remove_alert_valid_alert_name_choice_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alert",
            name="is_filtered",
        ),
    ]
