# Generated by Django 5.1.7 on 2025-07-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("impossible_travel", "0014_config_risk_score_increment_alerts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alert",
            name="notified",
        ),
        migrations.AddField(
            model_name="alert",
            name="notified_status",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Tracks each active_alerter status",
            ),
        ),
    ]
