# Generated by Django 5.1.6 on 2025-03-04 09:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("impossible_travel", "0014_remove_alert_valid_alert_name_choice_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="alert",
            name="valid_alert_name_choice",
        ),
        migrations.RemoveConstraint(
            model_name="config",
            name="valid_alert_filters_choices",
        ),
        migrations.AlterField(
            model_name="alert",
            name="name",
            field=models.CharField(
                choices=[
                    ("New Device", "Login from new device"),
                    ("Imp Travel", "Impossible Travel detected"),
                    ("New Country", "Login from new country"),
                    ("User Risk Threshold", "User risk_score increased"),
                    ("Anonymous IP Login", "Login from an anonymous IP"),
                    ("Atypical Country", "Login from an atypical country"),
                    ("Blocklist Ip", "Login from Blocklisted IP"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="config",
            name="filtered_alerts_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("New Device", "Login from new device"),
                        ("Imp Travel", "Impossible Travel detected"),
                        ("New Country", "Login from new country"),
                        ("User Risk Threshold", "User risk_score increased"),
                        ("Anonymous IP Login", "Login from an anonymous IP"),
                        ("Atypical Country", "Login from an atypical country"),
                        ("Blocklist Ip", "Login from Blocklisted IP"),
                    ],
                    max_length=50,
                ),
                blank=True,
                default=list,
                help_text="List of alerts' types to exclude from the alerting",
                null=True,
                size=None,
            ),
        ),
        migrations.AddConstraint(
            model_name="alert",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "name__in",
                        [
                            "New Device",
                            "Imp Travel",
                            "New Country",
                            "User Risk Threshold",
                            "Anonymous IP Login",
                            "Atypical Country",
                            "Blocklist Ip",
                        ],
                    )
                ),
                name="valid_alert_name_choice",
            ),
        ),
        migrations.AddConstraint(
            model_name="config",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "filtered_alerts_types__contained_by",
                        [
                            "New Device",
                            "Imp Travel",
                            "New Country",
                            "User Risk Threshold",
                            "Anonymous IP Login",
                            "Atypical Country",
                            "Blocklist Ip",
                        ],
                    ),
                    ("filtered_alerts_types__isnull", True),
                    _connector="OR",
                ),
                name="valid_alert_filters_choices",
            ),
        ),
    ]
