# Generated by Django 4.2.19 on 2025-06-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("impossible_travel", "0014_config_risk_score_increment_alerts"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="bruteforce_window",
            field=models.PositiveIntegerField(
                default=60,
                help_text="The time window in minutes used to detect potential brute-force login attempts.",
            ),
        ),
        migrations.AddField(
            model_name="login",
            name="aggregated_login_count",
            field=models.PositiveIntegerField(
                default=1,
                help_text="The number of unique aggregated login attempts matching during the aggregation window.",
            ),
        ),
        migrations.AddField(
            model_name="login",
            name="outcome",
            field=models.CharField(
                default="success",
                help_text="The outcome of the login attempt",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="login",
            name="window_start",
            field=models.DateTimeField(
                help_text="The start timestamp of the time window during which these unique aggregated login was observed.",
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="login",
            constraint=models.UniqueConstraint(
                fields=(
                    "user_id",
                    "index",
                    "country",
                    "user_agent",
                    "outcome",
                    "window_start",
                ),
                name="unique_login_aggregation",
            ),
        ),
    ]
