# Generated by Django 5.1.7 on 2025-06-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("impossible_travel", "0015_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                db_index=True,
                default=None,
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
