# Generated by Django 5.2.3 on 2025-07-06 04:53

import django.contrib.postgres.fields
import impossible_travel.models
import impossible_travel.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("impossible_travel", "0015_config_clean_invalid_countries"),
    ]

    operations = [
        migrations.AlterField(
            model_name="config",
            name="allowed_countries",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=20),
                blank=True,
                default=impossible_travel.models.get_default_allowed_countries,
                help_text="List of countries to exclude from the detection, because 'trusted' for the customer",
                null=True,
                size=None,
                validators=[impossible_travel.validators.validate_countries_names],
            ),
        ),
    ]
