# Generated by Django 5.2.3 on 2025-07-17 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("impossible_travel", "0015_remove_alert_notified_alert_notified_status"),
        ("impossible_travel", "0016_alter_config_allowed_countries"),
    ]

    operations = []
