# Generated by Django 5.2.4 on 2025-08-28 15:52

import django.contrib.postgres.fields
import impossible_travel.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("impossible_travel", "0016_alter_config_allowed_countries"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="alert",
            name="valid_alert_filter_type_choices",
        ),
        migrations.AddField(
            model_name="config",
            name="ignored_impossible_travel_all_same_country",
            field=models.BooleanField(
                default=True,
                help_text="If true, all the impossible travel alerts from and to the same country are ignored. If you want to exclude just some countries, use the 'ignored_impossible_travel_countries_couples' Config field instead",
            ),
        ),
        migrations.AddField(
            model_name="config",
            name="ignored_impossible_travel_countries_couples",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of country pairs (start_country, last_country) to ignore for impossible_travel alerts. Country names must match the names in the countries_list.json config file. Example: [['Italy', 'Italy'], ['United States', 'France']]",
                validators=[impossible_travel.validators.validate_country_couples_list],
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="filter_type",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        (
                            "ignored_users filter",
                            "Alert filtered because the user is ignored - the user is in the Config.ignored_users list or Config.enabled_users list is populated",
                        ),
                        (
                            "ignored_ips filter",
                            "Alert filtered because the IP is ignored - the ip is in the Config.ignored_ips list",
                        ),
                        (
                            "allowed_countries filter",
                            "Alert filtered because the country is whitelisted - the country is in the Config.allowed_countries list",
                        ),
                        (
                            "is_vip_filter",
                            "Alert filtered because the user is not vip - Config.alert_is_vip_only is True and the user is not in the Config.vip_users list",
                        ),
                        (
                            "alert_minimum_risk_score filter",
                            "Alert filtered because the User.risk_score is lower than the threshold set in Config.alert_minimum_risk_score",
                        ),
                        (
                            "filtered_alerts_types filter",
                            "Alert filtered because this detection type is excluded - the Alert.name detection type is in the Config.filtered_alerts_types list",
                        ),
                        (
                            "ignore_mobile_logins filter",
                            "Alert filtered because the login is from a mobile device - Config.ignore_mobile_logins is True",
                        ),
                        (
                            "ignored_ISPs filter",
                            "Alert filtered because the ISP is whitelisted - The ISP is in the Config.ignored_ISPs list",
                        ),
                        (
                            "ignored_all_same_country",
                            "Alert filtered because impossible travel alerts with the same origin and destination country are configured to be ignored (Config.ignored_impossible_travel_all_same_country)",
                        ),
                        (
                            "ignored_country_couple",
                            "Alert filtered because the specific origin–destination country pair is listed in the configuration, regardless of order (Config.ignored_impossible_travel_countries_couples)",
                        ),
                    ],
                    max_length=50,
                ),
                blank=True,
                default=list,
                help_text="List of filters that disabled the related alert",
                size=None,
            ),
        ),
        migrations.AddConstraint(
            model_name="alert",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "filter_type__contained_by",
                        [
                            "ignored_users filter",
                            "ignored_ips filter",
                            "allowed_countries filter",
                            "is_vip_filter",
                            "alert_minimum_risk_score filter",
                            "filtered_alerts_types filter",
                            "ignore_mobile_logins filter",
                            "ignored_ISPs filter",
                            "ignored_all_same_country",
                            "ignored_country_couple",
                        ],
                    ),
                    ("filter_type", []),
                    _connector="OR",
                ),
                name="valid_alert_filter_type_choices",
            ),
        ),
    ]
