# Generated by Django 5.1.7 on 2025-06-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("impossible_travel", "0016_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, db_index=True, max_length=255, null=True, unique=True
            ),
        ),
    ]
