# Generated by Django 5.2.4 on 2025-09-12 12:57

import django.contrib.postgres.fields
import impossible_travel.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "impossible_travel",
            "0017_remove_alert_valid_alert_filter_type_choices_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="config",
            name="alert_minimum_risk_score",
            field=models.CharField(
                choices=[
                    ("No risk", "User has no risk"),
                    ("Low", "User has a low risk"),
                    ("Medium", "User has a medium risk"),
                    ("High", "User has a high risk"),
                ],
                default="Medium",
                help_text="Select the risk_score that users should have at least to send the alerts",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="config",
            name="filtered_alerts_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("New Device", "Login from new device"),
                        ("Imp Travel", "Impossible Travel detected"),
                        ("New Country", "Login from new country"),
                        ("User Risk Threshold", "User risk_score increased"),
                        ("Anonymous IP Login", "Login from an anonymous IP"),
                        ("Atypical Country", "Login from an atypical country"),
                    ],
                    max_length=50,
                ),
                blank=True,
                default=impossible_travel.models.get_default_filtered_alerts_types,
                help_text="List of alerts' types to exclude from the alerting",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="config",
            name="ignore_mobile_logins",
            field=models.BooleanField(
                default=True,
                help_text="Flag to ignore mobile devices from the detection",
            ),
        ),
        migrations.AlterField(
            model_name="config",
            name="threshold_user_risk_alert",
            field=models.CharField(
                choices=[
                    ("No risk", "User has no risk"),
                    ("Low", "User has a low risk"),
                    ("Medium", "User has a medium risk"),
                    ("High", "User has a high risk"),
                ],
                default="Medium",
                help_text="Select the risk_score that a user should overcome to send the 'USER_RISK_THRESHOLD' alert",
                max_length=30,
            ),
        ),
    ]
