# Generated by Django 5.2.7 on 2025-10-28 16:38

from django.db import migrations, models


def set_default_execution_mode(apps, schema_editor):
    TaskSettings = apps.get_model("impossible_travel", "TaskSettings")
    for task in TaskSettings.objects.all():
        task.execution_mode = "automatic"
        task.save(update_fields=["execution_mode"])


class Migration(migrations.Migration):
    dependencies = [
        ("impossible_travel", "0019_remove_alert_valid_alert_filter_type_choices_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasksettings",
            name="execution_mode",
            field=models.CharField(
                choices=[("manual", "Manual"), ("automatic", "Automatic")],
                default="automatic",
                max_length=20,
            ),
        ),
        migrations.RunPython(set_default_execution_mode, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="tasksettings",
            constraint=models.UniqueConstraint(
                fields=["task_name", "execution_mode"],
                name="unique_task_execution_mode",
            ),
        ),
    ]
