# Generated by Django 5.2.7 on 2025-10-25 14:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("impossible_travel", "0019_remove_alert_valid_alert_filter_type_choices_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("security_threat", "Security Threat"),
                        ("network_issue", "Network Issue"),
                        ("configuration_error", "Configuration Error"),
                        ("user_activity", "User Activity"),
                        ("system_health", "System Health"),
                    ],
                    max_length=50,
                ),
                blank=True,
                default=list,
                help_text="List of predefined tags assigned to this alert",
                size=None,
            ),
        ),
        migrations.AddConstraint(
            model_name="alert",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("tags__contained_by", ["security_threat", "network_issue", "configuration_error", "user_activity", "system_health"]),
                    ("tags", []),
                    _connector="OR",
                ),
                name="valid_alert_tags_choices",
            ),
        ),
    ]
