# Generated by Django 5.2.7 on 2025-11-01 11:22

import django.contrib.postgres.fields
import impossible_travel.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("impossible_travel", "0019_remove_alert_valid_alert_filter_type_choices_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("security_threat", "Alert confirmed as real incident"),
                        ("under_investigation", "Alert to analyze"),
                        ("test_event", "Alert triggered during tests"),
                        ("network_issue", "Network Connectivity Issue"),
                        ("configuration_error", "System Configuration Error"),
                        ("user_activity", "Unusual User Activity"),
                        ("system_health", "System Health/Availability"),
                    ],
                    max_length=50,
                ),
                blank=True,
                default=list,
                help_text="List of Tags used to classify the alert. Multiple tags can be applied.",
                size=None,
                validators=[impossible_travel.validators.validate_tags],
            ),
        ),
    ]
