# Generated by Django 5.2.4 on 2025-11-24 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("impossible_travel", "0021_tasksettings_execution_mode_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fingerprint", models.CharField(db_index=True, max_length=255)),
                ("full_user_agent", models.CharField(db_index=True, max_length=255)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("times_seen", models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="tasksettings",
            name="unique_task_execution_mode",
        ),
        migrations.AddConstraint(
            model_name="tasksettings",
            constraint=models.UniqueConstraint(fields=("task_name", "execution_mode"), name="unique_task_execution"),
        ),
        migrations.AddField(
            model_name="userdevice",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to="impossible_travel.user",
            ),
        ),
        migrations.AddField(
            model_name="login",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="impossible_travel.userdevice",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userdevice",
            unique_together={("user", "fingerprint")},
        ),
    ]
