# Generated by Django 5.2.4 on 2025-12-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("impossible_travel", "0021_tasksettings_execution_mode_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="tasksettings",
            name="unique_task_execution_mode",
        ),
        migrations.AddConstraint(
            model_name="tasksettings",
            constraint=models.UniqueConstraint(fields=("task_name", "execution_mode"), name="unique_task_execution"),
        ),
    ]
