# Generated by Django 5.2.4 on 2025-12-01 13:49

from django.db import migrations, models
from ua_parser import user_agent_parser

from impossible_travel.models import Login


def populate_device_fingerprint(apps, schema_editor):
    # populate the new device_fingerprint field for existing logins
    UNKNOWN_OS = "unknownos"
    UNKNOWN_OS_MAJOR = "unknownosmajor"
    UNKNOWN_DEVICE = "unknowndevice"
    UNKNOWN_BROWSER = "unknownbrowser"

    UNKNOWN_FINGERPRINT = f"{UNKNOWN_OS}-{UNKNOWN_OS_MAJOR}-{UNKNOWN_DEVICE}-{UNKNOWN_BROWSER}"

    for login_db in Login.objects.all():
        if not login_db.user_agent:
            login_db.device_fingerprint = UNKNOWN_FINGERPRINT
            login_db.save()
            continue
        try:
            parsed = user_agent_parser.Parse(login_db.user_agent)
        except Exception:
            return UNKNOWN_FINGERPRINT

        os_data = parsed.get("os", {}) or {}
        ua_data = parsed.get("user_agent", {}) or {}
        device_data = parsed.get("device", {}) or {}

        os_family = (os_data.get("family") or UNKNOWN_OS).strip().lower()
        os_major = (os_data.get("major") or UNKNOWN_OS_MAJOR).strip().lower()
        device_family = (device_data.get("family") or UNKNOWN_DEVICE).strip().lower()
        browser_family = (ua_data.get("family") or UNKNOWN_BROWSER).strip().lower()

        agent_lower = login_db.user_agent.lower()

        # Heuristic for device type
        if any(x in agent_lower for x in ["x11", "win64", "wow64", "x86_64", "macintosh"]):
            device_family = "desktop"
        elif "tablet" in agent_lower or "ipad" in agent_lower:
            device_family = "tablet"
        elif "mobile" in agent_lower:
            device_family = "mobile"

        os_part = f"{os_family}-{os_major}".replace(" ", "")
        device_part = device_family.replace(" ", "")
        browser_part = browser_family.replace(" ", "")

        fingerprint = f"{os_part}-{device_part}-{browser_part}"

        # if all values are unkwown, return the fallback string
        if fingerprint == UNKNOWN_FINGERPRINT:
            res = UNKNOWN_FINGERPRINT

        res = fingerprint

        login_db.device_fingerprint = res
        login_db.save()


class Migration(migrations.Migration):

    dependencies = [
        ("impossible_travel", "0021_tasksettings_execution_mode_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="tasksettings",
            name="unique_task_execution_mode",
        ),
        migrations.AddField(
            model_name="login",
            name="device_fingerprint",
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name="tasksettings",
            constraint=models.UniqueConstraint(fields=("task_name", "execution_mode"), name="unique_task_execution"),
        ),
        migrations.RunPython(populate_device_fingerprint, migrations.RunPython.noop),
    ]
