# Generated by Django 5.2.4 on 2025-12-01 13:49

import logging

from django.db import migrations, models
from impossible_travel.models import Login
from ua_parser import user_agent_parser

logger = logging.getLogger(__name__)


def populate_device_fingerprint(apps, schema_editor):
    # Constants
    UNKNOWN_OS = "unknownos"
    UNKNOWN_OS_MAJOR = "unknownosmajor"
    UNKNOWN_DEVICE = "unknowndevice"
    UNKNOWN_BROWSER = "unknownbrowser"

    UNKNOWN_FINGERPRINT = (
        f"{UNKNOWN_OS}-{UNKNOWN_OS_MAJOR}-{UNKNOWN_DEVICE}-{UNKNOWN_BROWSER}"
    )

    logins_to_update = []
    batch_size = 500

    # Fetch all the logins, process them in memory
    for login_db in Login.objects.all():
        # Default fallback for unknown user agent
        if not login_db.user_agent:
            login_db.device_fingerprint = UNKNOWN_FINGERPRINT
            logins_to_update.append(login_db)
            continue

        try:
            parsed = user_agent_parser.Parse(login_db.user_agent)
        except Exception:
            # Log error in case of parsing failure and assign default fingerprint
            logger.exception(f"Error parsing user agent {login_db.user_agent}")
            login_db.device_fingerprint = UNKNOWN_FINGERPRINT
            logins_to_update.append(login_db)
            continue

        # Extract data from parsed user agent
        os_data = parsed.get("os", {}) or {}
        ua_data = parsed.get("user_agent", {}) or {}
        device_data = parsed.get("device", {}) or {}

        os_family = (os_data.get("family") or UNKNOWN_OS).strip().lower()
        os_major = (os_data.get("major") or UNKNOWN_OS_MAJOR).strip().lower()
        device_family = (device_data.get("family") or UNKNOWN_DEVICE).strip().lower()
        browser_family = (ua_data.get("family") or UNKNOWN_BROWSER).strip().lower()

        # Heuristic for device type detection
        agent_lower = login_db.user_agent.lower()

        # Heuristic for device type
        if any(
            x in agent_lower for x in ["x11", "win64", "wow64", "x86_64", "macintosh"]
        ):
            device_family = "desktop"
        elif "tablet" in agent_lower or "ipad" in agent_lower:
            device_family = "tablet"
        elif "mobile" in agent_lower:
            device_family = "mobile"

        # Construct the device fingerprint
        os_part = f"{os_family}-{os_major}".replace(" ", "")
        device_part = device_family.replace(" ", "")
        browser_part = browser_family.replace(" ", "")

        fingerprint = f"{os_part}-{device_part}-{browser_part}"

        # If fingerprint is unknown, use the fallback
        if fingerprint == UNKNOWN_FINGERPRINT:
            login_db.device_fingerprint = UNKNOWN_FINGERPRINT
        else:
            login_db.device_fingerprint = fingerprint

        logins_to_update.append(login_db)

        # Bulk update in batches
        if len(logins_to_update) >= batch_size:
            Login.objects.bulk_update(logins_to_update, ["device_fingerprint"])
            logins_to_update.clear()  # Clear the list after bulk update

    # Final bulk update for any remaining records
    if logins_to_update:
        Login.objects.bulk_update(logins_to_update, ["device_fingerprint"])


def check_regex_patterns(apps, schema_editor):
    """Check existing Config entries for unsafe regex patterns and log warnings.

    This is a non-blocking check that identifies existing dangerous patterns
    in ignored_users, enabled_users, and vip_users fields. Admins should
    review and update these patterns in the Django admin panel.
    """
    Config = apps.get_model("impossible_travel", "Config")
    from impossible_travel.modules.alert_filter import _is_safe_regex

    for config in Config.objects.all():
        for field_name in ["ignored_users", "enabled_users", "vip_users"]:
            patterns = getattr(config, field_name, []) or []
            if not patterns:
                continue

            unsafe = [p for p in patterns if not _is_safe_regex(p)]
            if unsafe:
                logger.warning(
                    f"[ReDoS Security Check] Config {config.id}: Found {len(unsafe)} unsafe regex pattern(s) "
                    f"in '{field_name}' field: {unsafe}. These patterns should be reviewed and updated in the "
                    f"Django admin panel to prevent potential Denial of Service attacks. See migration 0022 for details."
                )


class Migration(migrations.Migration):

    dependencies = [
        ("impossible_travel", "0021_tasksettings_execution_mode_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="tasksettings",
            name="unique_task_execution_mode",
        ),
        migrations.AddField(
            model_name="login",
            name="device_fingerprint",
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name="tasksettings",
            constraint=models.UniqueConstraint(
                fields=("task_name", "execution_mode"), name="unique_task_execution"
            ),
        ),
        migrations.RunPython(populate_device_fingerprint, migrations.RunPython.noop),
        migrations.RunPython(check_regex_patterns, migrations.RunPython.noop),
    ]
