# Generated by Django 5.2.9 on 2026-01-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impossible_travel', '0022_remove_tasksettings_unique_task_execution_mode_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='login',
            index=models.Index(fields=['timestamp'], name='impossible__timesta_afe402_idx'),
        ),
        migrations.AddIndex(
            model_name='login',
            index=models.Index(fields=['ip'], name='impossible__ip_53438a_idx'),
        ),
        migrations.AddIndex(
            model_name='login',
            index=models.Index(fields=['country'], name='impossible__country_b552b7_idx'),
        ),
        migrations.AddIndex(
            model_name='login',
            index=models.Index(fields=['index'], name='impossible__index_9fa32d_idx'),
        ),
        migrations.AddIndex(
            model_name='login',
            index=models.Index(fields=['event_id'], name='impossible__event_i_74ea43_idx'),
        ),
    ]
