# Generated by Django 5.2.10 on 2026-01-13 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impossible_travel', '0023_login_impossible__timesta_afe402_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='login',
            name='impossible__index_9fa32d_idx',
        ),
    ]
