# Generated by Django 5.2.10 on 2026-01-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impossible_travel', '0023_login_impossible__timesta_afe402_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(unique=True),
        ),
    ]
