# Generated by Django 4.2.19 on 2025-04-11 10:30

import django.contrib.postgres.fields
from django.db import migrations, models
import buffalogs.impossible_travel.models


class Migration(migrations.Migration):

    dependencies = [
        ("impossible_travel", "0013_remove_alert_valid_alert_name_choice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="risk_score_increment_alerts",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("New Device", "Login from new device"),
                        ("Imp Travel", "Impossible Travel detected"),
                        ("New Country", "Login from new country"),
                        ("User Risk Threshold", "User risk_score increased"),
                        ("Anonymous IP Login", "Login from an anonymous IP"),
                        ("Atypical Country", "Login from an atypical country"),
                    ],
                    max_length=50,
                ),
                default=impossible_travel.models.get_default_risk_score_increment_alerts,
                help_text="List of alert types to consider to increase the user risk_score",
                size=None,
            ),
        ),
    ]
